// Definitions shown in the audit slide-in panel: the formula, plain-English
// explanation, and source SOQL for each metric the HelpIcon can open.
export const AUDIT_DEFS = {
  rpd: { title: "Revenue per day (RPD)", formula: "SUM(Total_Billable_Amount_Formula__c) ÷ working days", detail: "Approved billable timecard splits only. Project sources: Managed Services, Post Project Managed Services, Network. Working days calculated from CA holiday calendar in Options.", soql: `SELECT SUM(Total_Billable_Amount_Formula__c) revenue\nFROM pse__Timecard__c\nWHERE pse__Approved__c = true\n  AND pse__Billable__c = true\n  AND Project_Source__c IN (\n    'Managed Services',\n    'Post Project Managed Services',\n    'Network'\n  )\n  AND pse__Start_Date__c >= [start]\n  AND pse__Start_Date__c <= [end]` },
  ceiling: { title: "Full utilization ceiling", formula: "Active billable resources × 8 hrs × working days × effective rate", detail: "Pulls all resources with active billable Scheduled assignments on managed service projects this month. Effective rate = pse__Bill_Rate__c if > 0, else pse__Planned_Bill_Rate__c. Assumes 8 hrs/working day at 100% capacity. No deductions for vacation, credited time, or bench.", soql: `SELECT pse__Resource__c,\n  pse__Bill_Rate__c,\n  pse__Planned_Bill_Rate__c\nFROM pse__Assignment__c\nWHERE pse__Is_Billable__c = true\n  AND pse__Status__c = 'Scheduled'\n  AND pse__Project__r.Project_Source__c\n    IN ('Managed Services', ...)\n  AND pse__Start_Date__c <= [month_end]\n  AND pse__End_Date__c >= [month_start]` },
  vacation: { title: "Vacation hours", formula: "Approved timecards on 'Internal - Vacation Time' project", detail: "Sums pse__Total_Hours__c from approved timecard splits where the project name equals 'Internal - Vacation Time'. Revenue impact is estimated: vacation hrs × resource's avg bill rate from trailing 4 weeks of billable managed services timecards.", soql: `SELECT pse__Resource__r.Name,\n  SUM(pse__Total_Hours__c) hrs\nFROM pse__Timecard__c\nWHERE pse__Approved__c = true\n  AND pse__Project__r.Name\n    = 'Internal - Vacation Time'\n  AND pse__Start_Date__c >= [start]\n  AND pse__Start_Date__c <= [end]\nGROUP BY pse__Resource__r.Name` },
  forecast: { title: "Forecast remaining revenue", formula: "Remaining scheduled assignment hours × effective bill rate", detail: "Active Scheduled assignments overlapping the remaining working days of the current month. Rate = Bill_Rate__c if > 0, else Planned_Bill_Rate__c. Hours prorated: Scheduled_Hours × (overlap days / total assignment days). Excludes vacation assignments.", soql: `SELECT pse__Resource__c,\n  pse__Scheduled_Hours__c,\n  pse__Bill_Rate__c,\n  pse__Planned_Bill_Rate__c,\n  pse__Start_Date__c,\n  pse__End_Date__c\nFROM pse__Assignment__c\nWHERE pse__Is_Billable__c = true\n  AND pse__Status__c = 'Scheduled'\n  AND pse__Project__r.Name\n    != 'Internal - Vacation Time'\n  AND pse__End_Date__c >= [today]\n  AND pse__Start_Date__c <= [month_end]` },
  working_days: { title: "Working days", formula: "Weekdays in period minus enabled statutory holidays", detail: "Client-side calculation. Counts Mon–Fri for the selected period, then subtracts any CA holidays toggled ON in Options. US holidays available separately. Toggle holidays off to exclude them from the working day count.", soql: "No Salesforce query — calculated from the Options holiday calendar." },
  pod_rpd: { title: "Pod RPD", formula: "Pod revenue ÷ working days. Pod = timecards grouped by Project Manager.", detail: "Groups approved billable timecard splits by pse__Project__r.pse__Project_Manager__r.Name within the director's Group. PM field used as pod signal — more reliable than Practice for Meghan's team.", soql: `SELECT\n  pse__Project__r.pse__Project_Manager__r.Name pm,\n  SUM(Total_Billable_Amount_Formula__c) rev\nFROM pse__Timecard__c\nWHERE pse__Approved__c = true\n  AND pse__Billable__c = true\n  AND pse__Project__r.pse__Group__r.Name\n    = '[director]'\n  AND pse__Start_Date__c >= [start]\nGROUP BY\n  pse__Project__r.pse__Project_Manager__r.Name` },
  variance: { title: "RPD variance", formula: "(Period A RPD − Period B RPD) ÷ Period B RPD × 100", detail: "Day-normalized comparison. Raw revenue variance can be misleading when months have different working day counts — RPD variance controls for that. A month with more working days will naturally have more revenue even at the same daily rate.", soql: "Calculated from two separate Salesforce queries — one per period — then divided by their respective working day counts before comparing." },
};
